spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file://C://Professional//Courses//Microservices//spring-cloud-config-server//spring-cloud-config-server//git-localconfig-repo
server:
  port: 8888
